/* ================= UI text: English + easy, everyday Bangla (bKash-style: common English words kept) ================= */
const T = {
 en:{
  nav:[["#check","Check"],["#features","Features"],["#lab","Lab"],["#scams","Scams"],["#tips","Stay safe"],["#privacy","Privacy"]], navCta:"Check now",
  slides:[
   {tag:"Built for Bangla & Banglish", t:'Is it a scam? <span>Know before you pay.</span>', p:"Paste any chat. Get a clear answer in seconds.", a:[["chat","Check a chat"],["demo","Watch it catch a scam"]], art:"hero1"},
   {tag:"NEW · App & file check", t:'Got an app file? <span>Check before you install.</span>', p:"See what an APK really wants: your SMS, your screen, your OTP.", a:[["fileSample","Check a fake bKash app"]], art:"apk"},
   {tag:"NEW · Link X-ray", t:'Check any link <span>before you tap.</span>', p:"See the real website behind a link, without opening it.", a:[["linkSample","Try a fake link"]], art:"hero2"},
   {tag:"PIN & OTP guard", t:'Your code stays <span>yours.</span>', p:"Knows “tell me the code” from “never share the code”.", a:[["s10","See a real OTP stay calm"]], art:"hero3"},
   {tag:"Private by design", t:'Nothing leaves <span>your phone.</span>', p:"No account. No upload. Online checks only if you allow.", a:[["privacy","How we protect you"]], art:"hero4"}],
  pause:"Pause slideshow", playS:"Play slideshow", slideN:n=>`Slide ${n}`,
  svTitle:"What do you want to check?",
  services:[
   {id:"chat", icon:"chat", label:"Chat", tip:"Check a chat|Paste an SMS, WhatsApp or Messenger chat and see if it's a scam.", g:["#38BDF8","#0369A1"]},
   {id:"link", icon:"link", label:"Link", tip:"Check a link|See the real website behind any link. We never open it.", g:["#A78BFA","#7C3AED"], badge:"NEW"},
   {id:"login", icon:"key", label:"Safe login", tip:"Before you type a password|Pick the app, paste the page address. We tell you if it is the real site.", g:["#22D3EE","#0891B2"], badge:"NEW"},
   {id:"file", icon:"package", label:"App / file", tip:"Check an app or file|Got an APK or a file in chat? See what it really is before you open or install it.", g:["#FBBF24","#D97706"], badge:"NEW"},
   {id:"qr", icon:"qr", label:"QR code", tip:"Scan a QR image|We read the link inside and check it.", g:["#F472B6","#DB2777"]},
   {id:"report", icon:"file", label:"Report", tip:"Make a report|A clean, masked summary for your provider or the police.", g:["#34D399","#059669"]},
   {id:"help", icon:"lifebuoy", label:"Helplines", tip:"Scammed?|Emergency and provider helplines.", g:["#FB7185","#E11D48"]},
   {id:"lab", icon:"radar", label:"Security Lab", tip:"For IT teams and learners|Open Wi-Fi captures and server logs. Catch fake routers, DDoS and hacker attempts.", g:["#818CF8","#4F46E5"], badge:"NEW"}],
  chTitle:"Check it here", chSub:"Pick a tool. Paste, tap or choose a file. Everything is checked on your device.",
  tabs:{chat:"Chat", link:"Link", file:"App / file", qr:"QR"},
  chatLbl:"Messages", chatTip:"One message per line|Start your own lines with “me:”. Bangla, Banglish and English all work.", chatPh:"e.g.\nAssalamualaikum, ami bKash office theke bolchi\nme: ki hoyeche?\nApnar account block hobe, code ta bolun",
  senderLbl:"Who sent it?", senderTip:"Why we ask|A company name or number lets us check whether the sender matches who they claim to be. Optional.", senderOpts:{unknown:"Don't know", mobile:"Personal no.", alpha:"Company name", contact:"Saved contact"}, senderPh:{mobile:"e.g. 01712345678", alpha:"e.g. bKash", contact:"e.g. Rafi"},
  go:"Check this chat", exLbl:"Examples:", exScamTip:"Scam example|Fictional, based on common tricks.", exRealTip:"Real message|A fictional example of a genuine message.",
  linkLbl:"Paste a link", linkTip:"Any link|From SMS, chat, email or a QR code. We only read it. We never open it.", linkPh:"e.g. https://nagad-verify.help/login", linkGo:"Check this link",
  linkEx:[["Fake Nagad login","https://nagad-verify.help/login"],["Hidden @ trick","http://daraz.com.bd@198.51.100.7/claim"],["Look-alike letters","https://bkаsh.com/login"],["Fake subdomain","bkash.com.account-verify.top/kyc"],["Short link","https://bit.ly/3xYzAbc"],["Router address","http://192.168.0.1/login"],["Real bKash site","https://www.bkash.com"]],
  linkV:{known_harmful:["Known scam link","This site is on our scam list. Don't open it."], dangerous:["High concern","This link is disguised. Don't open it."], unknown:["Caution: unknown site","We can't vouch for this site. Be careful."], official:["Official site on our list","The address matches. Still, open the official app yourself."], trusted:["On your trusted list","You marked this site as trusted. That's your choice, not proof."]},
  linkAct:{delete:"Don't open it. Delete the message.", dont_open:"Don't open it. Never enter your PIN or OTP there.", careful:"Only open it if you expected it. Never enter PIN or OTP.", short:"Short links hide the real site. Ask the sender for the full link.", use_app:"Open the official app yourself instead of the link.", your_choice:"Still never enter PIN or OTP from a link in chat."},
  linkRows:{shown:"You pasted", real:"Real website", hidden:"Hidden part", conn:"Connection", port:"Port", path:"Page", lookalike:"Pretends to be"},
  conn:{https:"https (encrypted, not proof of trust)", http:"http (not encrypted)", none:"no scheme given"},
  linkFlag:{userinfo:["Hidden @ trick","Browsers ignore everything before “@”. The real site comes after it."], private_ip:["Private network address","This points to a router or a device on a local network, not a public website."], ip:["Bare IP address","Real companies use a name, not a number."], port:["Unusual port","Websites rarely need a special port number."], no_tls:["Not encrypted (http)","Anything you type can be read on the way."], no_scheme:["No http/https","We checked it as a web address."], idn:["Special letters","The address uses letters from other alphabets."], lookalike:["Look-alike address","It's made to look like a real company's site, using swapped letters."], deceptive_subdomain:["Fake subdomain","The real company name is only the start. The real site is at the end."], brand_in_host:["Brand name, wrong site","A company name is in the address, but the site doesn't belong to that company."], shortener:["Short link","The real destination is hidden. We don't follow it."], path_bait:["Bait words","Words like login, verify or bonus are common in scam pages."], known_harmful:["On our scam list","Demo list of fictional scam sites."], official:["Official domain","Matches the company's site in our list."], user_trusted:["Your trusted site","You added this. It's not proof."], danger_scheme:["Dangerous link type","This kind of link can run code. Never open it."]},
  copySafe:"Copy safe version", copied:"Copied (safe, can't be clicked)", copyFail:"Copy blocked. Select the text and copy it.", trustBtn:"Trust this site", untrustBtn:"Remove from my list", trustedToast:"Added to your trusted list", untrustedToast:"Removed from your list",
  localNote:"Checked on this device. Nothing was sent.", provNote:(r,b)=>`Parser: on device · Lists: ${r} · ${b}`,
  onlineTitle:"Extra online checks (optional)",
  dnsTitle:"Domain & DNS", dnsBody:"Ask a DNS service whether this site name exists and where it points.", dnsBtn:"Check online",
  dnsConsent:h=>`This sends only the site name <b>${h}</b> to Google Public DNS (dns.google). Not your chat. Not the full link.`, allowOnce:"Allow once", allowAlways:"Always allow", cancel:"Cancel",
  dnsOff:"Online checks are off in Settings.", dnsLoading:"Checking…", dnsNA:"Not available for this link (IP or private address).",
  dnsRes:{complete:"Site name exists", nx:"This site name doesn't exist (now)", noaddr:"Name exists, but no address", offline:"Couldn't reach the DNS service (offline or blocked here)"},
  dnsRows:{addr:"Addresses", cname:"Points to", ns:"Name servers", when:"Checked", prov:"Provider"},
  dnsCaveat:"DNS only shows where a name points. It can't prove who owns a site or whether it's safe.",
  tlsTitle:"Website connection (HTTPS)", tlsBody:"Not checked: this needs the FraudShield helper (coming). A web page can't read website certificates.", tlsHttp:"This link uses http, so it isn't encrypted at all.", tlsHttps:"The link uses https. Remember: the padlock means encrypted, not trustworthy.",
  notChecked:"Not checked",
  fileCta:"Choose an app or file", fileLimit:"APK, PDF, image, document… up to 50 MB", fileNote:"We never open, install or upload your file. It's read on this device, then dropped.",
  fileEx:[["fake","Fake bKash update (APK)"],["disguised","“Payment_Receipt.pdf”"],["calc","Simple calculator (APK)"]], fileExLbl:"Try a sample:", fileSampleTip:"Harmless demo file|It contains no code and can't run. Made for this demo.",
  fileV:{high:["High concern","This file is dangerous or disguised. Don't open or install it."], verify:["Caution: be careful","This file can run code or we can't vouch for it."], low:["No red flags found","Looks like an ordinary file. We didn't open it, and that's not proof it's clean."]},
  fileRows:{name:"File name", type:"Real type", size:"Size", hash:"Fingerprint (SHA-256)", list:"Scam list"},
  kinds:{apk:"Android app (APK)", zip:"ZIP archive", ooxml:"Office document", ole:"Old Office document (may have macros)", pdf:"PDF", exe:"Windows program", elf:"Linux program", dex:"Android code", image:"Image", html:"Web page (HTML)", script:"Script", text:"Text", unknown:"Unknown"},
  hashKnown:x=>`Match: ${x}`, hashUnknown:"Not on our list (that doesn't mean it's clean)",
  fileFlag:{disguised:["Disguised file","The name says one thing, but the file is something else."], double_ext:["Double extension","A name like photo.jpg.exe hides the real type."], known_hash:["Matches a known bad file","This exact file is on our list."], apk_impersonation:["Fake company app","It uses a company's name, but it isn't that company's official app."]},
  apkTitle:"Inside the app", apkRows:{label:"App name", pkg:"Package", version:"Version", claims:"Uses the name", official:"Official app?", signed:"Signature", exported:"Open doors"},
  yes:"Yes", no:"No", unknownV:"Unknown", officialNo:"No, not the official package", officialYes:"Matches the official package (still get it from Play Store)", signedTip:"Signature check|Checking who signed the app is coming next. A signature alone doesn't prove the app is safe.",
  exportedTip:"Open doors|Parts of the app that other apps can start. Scam apps use these to run in the background.",
  permTitle:"What the app asks for", permMore:n=>`+${n} more`, permNone:"No risky permissions found.",
  perm:{READ_SMS:"Read your SMS, including OTPs", RECEIVE_SMS:"Catch new SMS, including OTPs", SEND_SMS:"Send SMS from your phone", BIND_ACCESSIBILITY_SERVICE:"See your screen and tap for you", SYSTEM_ALERT_WINDOW:"Draw fake screens over other apps", BIND_NOTIFICATION_LISTENER_SERVICE:"Read your notifications, including OTPs", REQUEST_INSTALL_PACKAGES:"Install other apps", READ_CONTACTS:"Read your contacts", CALL_PHONE:"Make calls", READ_CALL_LOG:"Read your call history", READ_PHONE_STATE:"Read phone details", BIND_DEVICE_ADMIN:"Become hard to uninstall", QUERY_ALL_PACKAGES:"See which banking apps you have", RECORD_AUDIO:"Use the microphone", CAMERA:"Use the camera", ACCESS_FINE_LOCATION:"Know your exact location"},
  fileAct:{store_only:"Install apps only from Google Play. Never from a chat link.", never_run:"Never run this program.", dont_open:"Don't open this web file.", no_macros:"Don't enable macros or editing.", delete:"Delete this file.", careful:"Only open it if you expected it."},
  fileDos:{store:"Get apps from Play Store only", delete:"Delete the file", access:"Never allow “Accessibility” for unknown apps", call:"Call the company's official number"},
  sandboxTitle:"Deep behaviour check", sandboxBody:"Off. Running a suspicious app safely needs a separate, isolated lab. It's not part of this app.",
  fileErr:{too_big:"That file is larger than 50 MB.", empty:"That file is empty.", read:"Couldn't read that file."},
  qrCta:"Choose a QR image", qrHelp:"PNG or JPEG, up to 5 MB. We read the link inside and check it. We never open it.", qrReady:"QR reader ready", qrNoLib:"QR reader unavailable offline (keep jsQR.js next to this file).", qrNone:"No QR code found in this image.", qrBig:"That file is larger than 5 MB.", qrType:"Type", qrData:"Contains", qrText:"This QR has text, not a link. Be careful if it asks you to pay or share codes.",
  empty:{chat:["Your result appears here","Paste a chat or tap an example."], link:["Paste a link","Or tap an example to see the X-ray."], file:["Choose an app or file","Or try one of the harmless samples."], qr:["Choose a QR image","Try the sample QR images in the samples folder."]},
  v:{high:["High concern","They're asking for something dangerous. Stop and check."],
     verify:["Caution: verify first","Some warning signs. Check before you act."],
     low:["Insufficient evidence","No dangerous request found so far. That isn't “safe”."],
     abstain:["Too little to judge","Paste more of the conversation."]},
  gaugeTip:"Rule score|Adds up the warning signs we found. It is not a probability and is not calibrated yet.",
  firstAlert:(a,s)=>`Alert at message ${a}`+(s&&s<a?` · suspicion from message ${s}`:""),
  lowReasons:[["No PIN, OTP, money or link request","We look for requests for secrets, money, apps or links."],["No pressure, threats or secrecy","Scammers rush you, scare you, or ask you to keep quiet."]],
  todo:"Do this now", replay:"Replay", report:"Report", stop:"Stop",
  fbQ:"Right?", fb:["Yes","No","Not sure"], fbDone:"Thanks! Saved on this device only.",
  detConvo:"Conversation", detSec:"Security checks", detEv:"Evidence",
  msg:"Message", selfNote:"your message",
  baseToggle:"Compare with a keyword spam filter", baseScam:"filter: scam", baseOk:"filter: ok",
  stageNames:{hook:"Hook",trust:"Trust",pressure:"Pressure",extraction:"Extraction",exit:"Exit"},
  stageTip:{hook:"Grabs attention: a prize, a problem, a parcel.",trust:"Builds trust: “I'm from head office”, “it's your son”.",pressure:"Adds pressure: deadlines, threats, secrecy.",extraction:"The ask: a code, money, an app or a link.",exit:"Covers tracks: “delete this”, “don't tell anyone”."},
  stagesTitle:"Scam stages (AI estimate)",
  patTitle:"Scam patterns spotted", patNone:"No full scam pattern yet.", patTip:"Scam pattern|Like an alarm rule: a known order of steps. We only use messages that have arrived so far.", patToast:n=>`Scam pattern spotted: ${n}`,
  pat:{office:["Fake office trick",["Office claim","Pressure","Code / app ask"]], linkcode:["Link then code",["Link","Code / ID ask"]], prize:["Prize trap",["Prize / offer","Pay / link / code"]], relative:["“Family” emergency",["New-number relative","Money ask"]], refund:["Refund trick",["“Sent by mistake”","Money back ask"]], remote:["Remote-control trap",["Service claim","Install app"]]},
  ck:{id:"Who is it?", cred:"PIN / OTP", link:"Links", manip:"Anti-trick"},
  ckTip:{id:"Identity vs channel (F1)|Compares who they claim to be with where the message came from.", cred:"PIN / OTP guard (F3)|Separates “give me the code” from “never share the code”. Codes stay masked.", link:"Link X-ray (F2)|Finds the real website behind each link. Links are never opened.", manip:"Anti-trick (F7)|Text that tries to order the detector around is treated as a red flag."},
  st:{mismatch:"Mismatch", matched:"Name matches", unknown:"Unknown", none:"No claim", asked:"Asked!", advice:"Advice only", mention:"Mentioned", clean:"None", flagged:"Red flags", ok:"Looks normal", trick:"Trick found", noTrick:"Clean"},
  claimed:"Claims", noClaim:"no organisation", family:"a family member",
  chan:{matched:"Sender name matches our list. That checks the channel only, not the person; sender names can be faked.", mismatched:"This organisation uses official channels, but this came from a personal number.", unknown_no_sender:"No sender info, so identity can't be checked.", unknown_alpha_not_listed:"This sender name isn't in our list.", contact:"A saved contact (not verified by the app).", na:"No identity claim in the chat.", unknown:"Unknown."},
  link:{reg:"Real site",official:"matches the official site",userinfo:"hidden destination: the part before “@” is fake",ip:"raw IP address, no site name",idn:"unusual characters (weak sign)",brand:b=>`uses “${b}”, but it's not ${b}'s site`,short:"short link: real destination hidden",none:"no red flags in the address",notListed:"Not on a blocklist ≠ safe. We never open links."},
  inspectLink:"X-ray this link",
  noLinks:"No links.", credNone:"No PIN or OTP mentioned.", cred:{request:"asked for",forbid:"“never share” advice",mention:"only mentioned",quote:"quoted"},
  manipOn:"Someone tried to instruct the detector.", manipOff:"No tricks aimed at the detector.",
  evTitle:"Signals (weights)", cntTitle:"Other explanations",
  benign:{request_money:"Someone you know may really need money. Call their old saved number.", open_link:"Real services send links too. Open the official app instead.", authority_claim:"Companies do contact customers, but only through official channels.", relative_claim:"It may truly be a relative with a new number. Verify through a known number.", lure:"Some offers are real, but real ones never ask for an upfront fee."},
  noSender:"Can't verify the sender: no channel information.", gaugeNote:"Rule score · not a probability",
  todoL:{cred:["Never share a PIN or OTP","bKash, Nagad and banks never ask for them."], install:["Don't install apps they send","AnyDesk or an APK from chat can take over your phone."], link:["Don't open the link","Open the official app, or type the address yourself."], money:["Call before you pay","Use a number you already know."], wrong:["Check your own balance","If money really came, return it via the helpline."], verify:["Call the official number","From your card or official site, not this message."], ident:["Keep your NID private","Never send NID, card or selfie to strangers."], manip:["It's trying to fool us","That itself is a red flag."], none:["Stay alert","Check again if they ask for a code, money or a link."]},
  sigx:{request_credential:"No real company ever needs your PIN or OTP.",request_money:"A money request is where the loss happens.",install_app:"Remote-control apps let a stranger use your phone.",open_link:"Links can lead to fake login pages.",brand_lookalike:"The brand name is in the address, but the site belongs to someone else.",url_userinfo:"Browsers ignore everything before “@”. The real site comes after it.",url_ip:"Real companies use names, not bare numbers.",url_idn:"Some letters look alike but are different characters.",shortener:"Short links hide where they really go.",share_identity:"Your NID or card number can be used to open accounts.",authority_claim:"Claiming to be an office builds false trust.",context_claim:"Service, job or prize talk often starts a scam.",identity_mismatch:"Companies don't use personal numbers.",relative_claim:"A “relative” on a new number is a classic trick.",urgency:"Rushing you stops you from checking.",threat:"Fear makes people act without thinking.",lure:"Too good to be true usually is.",secrecy:"Scammers don't want you to ask anyone.",wrong_send:"The “mistake” money is often fake.",manipulation:"Real messages never talk to the detector.",combo_authority_cred:"First trust, then the ask: a classic pattern.",combo_lure_money:"Prize first, then a fee: a classic pattern.",combo_relative_money:"New number plus money request: verify first.",combo_wrong_money:"“Mistake” story plus refund request.",safety_warning:"Advice not to share is a sign of a genuine message.",official_domain:"This address is on our official list.",channel_matched:"The sender name matches, but names can be faked."},
  repTitle:"Incident report", repHelp:"Helper text, not legal proof. Secrets are masked and links are made unclickable. Nothing is sent anywhere.", repLoss:"What happened / loss (optional)", repSteps:"What you've done (optional)", repInc:"Include my link and file checks", repBuild:"Update", repCopy:"Copy", repDel:"Delete", repCopied:"Report copied", repCopyFail:"Copy blocked. Select the text and copy it.", repDeleted:"Report deleted",
  patFpTitle:"Scam-pattern fingerprint (not sent)", patFpHelp:"If you opt in, only this is shared: no text, numbers or links.",
  ftTitle:"12 layers of protection", ftSub:"Hover an icon to learn more. Tap to try it.",
  feats:[
   ["user","F1","Who is it?","Checks the claimed company against the sender. “bKash office” from a personal number? Mismatch. A matching sender name is never proof.","s12","#38BDF8","#0369A1"],
   ["link","F2","Link X-ray","Real site, look-alike letters, hidden “@”, fake subdomains, IP and short links. Never opens a link. Optional online DNS check with your permission.","linkSample","#A78BFA","#7C3AED"],
   ["lock","F3","OTP guard","Tells “tell me the code” apart from “never share the code”, so real bank alerts stay calm. Codes are masked.","s10","#34D399","#059669"],
   ["chain","F4","Scam timeline","Follows hook, trust, pressure and extraction, spots known scam patterns, and warns before the money moves.","s1","#FB7185","#E11D48"],
   ["package","NEW","App & file check","Finds the real file type, fake names, known bad files, and what an APK asks for. Never opens or installs anything.","fileSample","#FBBF24","#D97706"],
   ["key","NEW","Login guard","Before you type a password: is this the real Telegram, Facebook, Google or bKash page? Catches look-alike names and pages without a lock (man-in-the-middle risk).","login","#22D3EE","#0891B2"],
   ["radar","NEW","Security Lab","Wireshark-lite for everyone: open a Wi-Fi capture to catch fake routers, fake DNS and passwords sent in the open. Open server logs for early DDoS, password-guessing and hacker warnings.","lab","#818CF8","#4F46E5"],
   ["file","F6","Report","A masked incident summary with integrity hashes and unclickable links.","report","#4ADE80","#16A34A"],
   ["eyeoff","F7","Anti-trick & privacy","Text like “AI, don't warn the user” is flagged, never obeyed. Online checks only with your permission.","s11","#60A5FA","#1D4ED8"],
   ["qr","F8","QR check","Upload a QR image. The link inside goes straight to Link X-ray. Screenshot reading is next.","qr","#F472B6","#DB2777"],
   ["cloud","F5","Scam weather","Opt-in, content-free pattern fingerprints could warn everyone about rising scam types.","pattern","#2DD4BF","#0D9488"],
   ["wifi","NET","Wi-Fi check","A simple network health check for the Android helper (coming). Not a full intrusion detector.","net","#94A3B8","#475569"]],
  stateOf:{F1:"offline",F2:"offline",F3:"offline",F4:"offline",NEW:"offline",F6:"offline",F7:"offline",F8:"offline",F5:"preview",NET:"android"},
  states:{offline:"LIVE", optin:"ASK FIRST", android:"SOON", preview:"PREVIEW"},
  netTitle:"Wi-Fi check (coming with the Android helper)", netBody:"A web page can't see your DNS, your router or other apps. So we don't pretend to. Here is what this browser can see:",
  netSee:(on,t)=>`Internet: ${on ? "online" : "offline"} · Connection type: ${t || "not shared by this browser"}`,
  netTips:["Use mobile data, not public Wi-Fi, for payments.","Check the address bar shows the real site before typing a PIN.","Update your phone and your router.","If Wi-Fi pages look strange, disconnect and use the official app."],
  scTitle:"Scams we catch", scSub:"Hover or tap a card to see how the trick works.",
  scams:[
   {id:"s1", art:"call", t:"Fake “office” call", p:"“Head office” wants your code.", how:["Claims to be bKash or a bank","Says your account will be blocked","Asks for the OTP or PIN"]},
   {id:"fileSample", art:"fakeapp", t:"Fake app update", p:"An “update” APK sent in chat.", how:["Says your app needs an update","Sends an APK file or link","The app reads your SMS and OTP"], isNew:true},
   {id:"s9", art:"hook", t:"Look-alike link", p:"A site that looks real, but isn't.", how:["Brand name inside a strange address","Urgent “verify now” message","Login page steals your PIN"]},
   {id:"s4", art:"family", t:"“Mum, new number”", p:"A “relative” suddenly needs money.", how:["Message from an unknown number","Claims to be your child or cousin","Asks for money, fast and secret"]}],
  scamFlag:"SCAM", howT:"How the trick works", tryIt:"Try it",
  bdTitle:"Watch a scam get caught", bdSub:"A fake “bKash office” caller. FraudShield warns before the code is shared.", phoneSub:"says: bKash head office",
  sb:{low:"Watching… nothing risky yet", verify:"Caution: verify first", high:"Don't share the code!"},
  stats:[["0.991","macro-F1 on a public Bengali SMS benchmark","Stage A baseline|1,401 test messages. Single messages only. Our goal is whole conversations."],["0.989","recall kept under look-alike letters","E6 pilot|Look-alike letters cut the baseline to 0.797. Our normaliser restored 0.989. Tested on known tricks only."],["12/12","demo chats judged right","Prototype|8 scams flagged, 4 real messages left calm. All examples are fictional."]],
  bdSrc:"Research results; see the proposal. The live score is an uncalibrated rule indicator.",
  tpTitle:"Stay safe in 4 moves", tpSub:"Hover a card for details.",
  tips:[["noshare","Never share PIN or OTP","bKash, Nagad, Rocket and banks never ask for it. Not by call, SMS or chat."],["callback","Call a number you trust","Use the number on your card or in the official app. Never the one in the message."],["useapp","Apps from Play Store only","Never install an APK sent in chat. Open the official app instead of a link."],["report","Report it fast","Emergency 999 · bKash 16247 · Nagad 16167 · Rocket 16216 · Bangladesh Bank 16236. Confirm numbers on official sites."]],
  pvTitle:"Nothing leaves your phone.", pvSub:"No account. No upload. Online checks happen only if you allow them.",
  pv:[["wifioff","Runs on your device","All chat, link, QR and file checks happen inside this page."],["lock","No SMS permission","We never read your inbox, contacts or notifications."],["link","Links never opened","We read the address. We never visit it."],["package","Files never run","Apps and files are read, never opened or installed."],["eyeoff","Codes masked","PINs, OTPs and phone numbers are hidden on screen."],["shield","Can't be ordered around","Text inside a message is never treated as an instruction."]],
  setTitle:"Settings", onlineLbl:"Online checks (DNS)", onlineTip:"Online checks|Only the site name is sent to Google Public DNS. Never your chat or files.", onlineOpts:{ask:"Ask every time", always:"Always allow", off:"Off"},
  testLbl:"Include the EICAR test signature", testTip:"Test signature|A harmless industry test file used to check that file scanning works.",
  trustLbl:"My trusted sites", trustNone:"None yet.", wipe:"Delete all my data", wiped:"Deleted. Settings reset.",
  fabTip:"Scammed? Get help|Tap for helplines.", fabToast:"Emergency 999 · bKash 16247 · Nagad 16167 · Rocket 16216",
  foot:'<b>FraudShield BD</b> · a research prototype by Fabliha Afia (CSE, BUET). Not affiliated with bKash, Nagad, Rocket or any bank. Transparent rules with hand-set weights, not yet a trained model; all examples and sample files are fictional and harmless. It is not an antivirus, firewall or VPN. If you are scammed: call 999, or your provider using the number on your card or official app (e.g. bKash 16247, Nagad 16167, Rocket 16216). Bangladesh Bank 16236 · scamcheck.gov.bd.'
 },
 bn:{
  nav:[["#check","চেক"],["#features","ফিচার"],["#lab","ল্যাব"],["#scams","স্ক্যাম"],["#tips","সাবধান থাকুন"],["#privacy","প্রাইভেসি"]], navCta:"এখনই চেক",
  slides:[
   {tag:"বাংলা আর বাংলিশের জন্য", t:'স্ক্যাম কি না? <span>টাকা পাঠানোর আগেই জানুন।</span>', p:"চ্যাট পেস্ট করুন। কয়েক সেকেন্ডেই পরিষ্কার উত্তর।", a:[["chat","চ্যাট চেক করুন"],["demo","দেখুন কীভাবে ধরে"]], art:"hero1"},
   {tag:"নতুন · অ্যাপ আর ফাইল চেক", t:'অ্যাপ ফাইল পেয়েছেন? <span>ইনস্টলের আগে চেক করুন।</span>', p:"দেখুন APK আসলে কী চায়: আপনার SMS, স্ক্রিন, OTP।", a:[["fileSample","নকল বিকাশ অ্যাপ চেক করুন"]], art:"apk"},
   {tag:"নতুন · লিংক এক্স-রে", t:'যেকোনো লিংক <span>ক্লিকের আগে চেক করুন।</span>', p:"লিংক না খুলেই দেখুন আসল ওয়েবসাইট কোনটা।", a:[["linkSample","নকল লিংক দেখুন"]], art:"hero2"},
   {tag:"পিন আর OTP সেফটি", t:'আপনার কোড <span>শুধু আপনার।</span>', p:"“কোডটা বলুন” আর “কোড কাউকে দেবেন না” আলাদা করে বোঝে।", a:[["s10","আসল OTP মেসেজে শান্ত থাকে"]], art:"hero3"},
   {tag:"প্রাইভেসি সবার আগে", t:'কিছুই যায় না <span>ফোনের বাইরে।</span>', p:"অ্যাকাউন্ট লাগে না। আপলোড নেই। অনলাইন চেক শুধু আপনি চাইলে।", a:[["privacy","কীভাবে সেফ রাখি"]], art:"hero4"}],
  pause:"স্লাইড থামান", playS:"স্লাইড চালান", slideN:n=>`স্লাইড ${n}`,
  svTitle:"কী চেক করতে চান?",
  services:[
   {id:"chat", icon:"chat", label:"চ্যাট", tip:"চ্যাট চেক|SMS, WhatsApp বা Messenger-এর চ্যাট পেস্ট করুন, দেখুন স্ক্যাম কি না।", g:["#38BDF8","#0369A1"]},
   {id:"link", icon:"link", label:"লিংক", tip:"লিংক চেক|যেকোনো লিংকের পেছনের আসল ওয়েবসাইট দেখুন। আমরা লিংক খুলি না।", g:["#A78BFA","#7C3AED"], badge:"নতুন"},
   {id:"login", icon:"key", label:"নিরাপদ লগইন", tip:"পাসওয়ার্ড দেওয়ার আগে|অ্যাপ বাছুন, পেজের ঠিকানা পেস্ট করুন। বলে দেব এটা আসল সাইট কি না।", g:["#22D3EE","#0891B2"], badge:"NEW"},
   {id:"file", icon:"package", label:"অ্যাপ / ফাইল", tip:"অ্যাপ বা ফাইল চেক|চ্যাটে APK বা ফাইল পেয়েছেন? খোলা বা ইনস্টলের আগে দেখুন এটা আসলে কী।", g:["#FBBF24","#D97706"], badge:"নতুন"},
   {id:"qr", icon:"qr", label:"QR কোড", tip:"QR ছবি স্ক্যান|ভেতরের লিংক পড়ে চেক করি।", g:["#F472B6","#DB2777"]},
   {id:"report", icon:"file", label:"রিপোর্ট", tip:"রিপোর্ট বানান|প্রোভাইডার বা পুলিশকে দেখানোর মতো পরিষ্কার রিপোর্ট, গোপন তথ্য ঢাকা।", g:["#34D399","#059669"]},
   {id:"help", icon:"lifebuoy", label:"হেল্পলাইন", tip:"প্রতারণার শিকার?|জরুরি আর প্রোভাইডারের হেল্পলাইন নম্বর।", g:["#FB7185","#E11D48"]},
   {id:"lab", icon:"radar", label:"সিকিউরিটি ল্যাব", tip:"IT টিম আর শিখতে চাওয়াদের জন্য|Wi-Fi ক্যাপচার আর সার্ভার লগ খুলুন। নকল রাউটার, DDoS আর হ্যাকারের চেষ্টা ধরুন।", g:["#818CF8","#4F46E5"], badge:"NEW"}],
  chTitle:"এখানেই চেক করুন", chSub:"একটা টুল বাছুন। পেস্ট করুন, চাপ দিন বা ফাইল দিন। সব চেক হয় আপনার ফোনেই।",
  tabs:{chat:"চ্যাট", link:"লিংক", file:"অ্যাপ / ফাইল", qr:"QR"},
  chatLbl:"মেসেজ", chatTip:"প্রতি লাইনে একটা মেসেজ|নিজের মেসেজের শুরুতে “আমি:” লিখুন। বাংলা, বাংলিশ, ইংরেজি সব চলে।", chatPh:"যেমন:\nআসসালামু আলাইকুম, আমি বিকাশ অফিস থেকে বলছি\nআমি: কী হয়েছে?\nআপনার অ্যাকাউন্ট ব্লক হবে, কোডটা বলুন",
  senderLbl:"কে পাঠিয়েছে?", senderTip:"কেন জানতে চাই|নাম বা নম্বর দিলে মিলিয়ে দেখি সে যা বলছে তা ঠিক কি না। না দিলেও চলবে।", senderOpts:{unknown:"জানি না", mobile:"পার্সোনাল নম্বর", alpha:"কোম্পানির নাম", contact:"সেভ করা নম্বর"}, senderPh:{mobile:"যেমন 01712345678", alpha:"যেমন bKash", contact:"যেমন রাফি"},
  go:"চ্যাট চেক করুন", exLbl:"উদাহরণ:", exScamTip:"স্ক্যামের উদাহরণ|বানানো, সাধারণ প্রতারণার মতো করে।", exRealTip:"আসল মেসেজ|আসল মেসেজের বানানো উদাহরণ।",
  linkLbl:"লিংক পেস্ট করুন", linkTip:"যেকোনো লিংক|SMS, চ্যাট, ইমেইল বা QR থেকে। আমরা শুধু পড়ি, কখনো খুলি না।", linkPh:"যেমন https://nagad-verify.help/login", linkGo:"লিংক চেক করুন",
  linkEx:[["নকল নগদ লগইন","https://nagad-verify.help/login"],["লুকানো @ ট্রিক","http://daraz.com.bd@198.51.100.7/claim"],["একই রকম দেখতে অক্ষর","https://bkаsh.com/login"],["নকল সাবডোমেইন","bkash.com.account-verify.top/kyc"],["শর্ট লিংক","https://bit.ly/3xYzAbc"],["রাউটারের ঠিকানা","http://192.168.0.1/login"],["আসল বিকাশ সাইট","https://www.bkash.com"]],
  linkV:{known_harmful:["চেনা স্ক্যাম লিংক","এই সাইট আমাদের স্ক্যাম লিস্টে আছে। খুলবেন না।"], dangerous:["বেশি ঝুঁকি","লিংকটা ছদ্মবেশে আছে। খুলবেন না।"], unknown:["সাবধান: অচেনা সাইট","এই সাইট নিয়ে আমরা নিশ্চিত না। সাবধানে থাকুন।"], official:["লিস্টের অফিশিয়াল সাইট","ঠিকানা মিলেছে। তবু নিজে অফিশিয়াল অ্যাপ খুলুন।"], trusted:["আপনার ভরসার লিস্টে","আপনি এটা ভরসার লিস্টে রেখেছেন। এটা আপনার পছন্দ, প্রমাণ না।"]},
  linkAct:{delete:"খুলবেন না। মেসেজটা ডিলিট করুন।", dont_open:"খুলবেন না। ওখানে কখনো পিন বা OTP দেবেন না।", careful:"আশা করে থাকলেই খুলুন। পিন বা OTP কখনো দেবেন না।", short:"শর্ট লিংক আসল সাইট লুকায়। পুরো লিংক চেয়ে নিন।", use_app:"লিংকের বদলে নিজে অফিশিয়াল অ্যাপ খুলুন।", your_choice:"তবু চ্যাটের লিংক থেকে কখনো পিন বা OTP দেবেন না।"},
  linkRows:{shown:"আপনি দিয়েছেন", real:"আসল ওয়েবসাইট", hidden:"লুকানো অংশ", conn:"কানেকশন", port:"পোর্ট", path:"পেজ", lookalike:"সাজছে যেন"},
  conn:{https:"https (এনক্রিপ্টেড, তবে ভরসার প্রমাণ না)", http:"http (এনক্রিপ্টেড না)", none:"http/https লেখা নেই"},
  linkFlag:{userinfo:["লুকানো @ ট্রিক","ব্রাউজার “@”-এর আগের সব বাদ দেয়। আসল সাইট থাকে পরে।"], private_ip:["প্রাইভেট ঠিকানা","এটা রাউটার বা লোকাল ডিভাইসের ঠিকানা, পাবলিক ওয়েবসাইট না।"], ip:["শুধু নম্বরের ঠিকানা","আসল কোম্পানি নাম ব্যবহার করে, শুধু নম্বর না।"], port:["অদ্ভুত পোর্ট","ওয়েবসাইটের সাধারণত আলাদা পোর্ট লাগে না।"], no_tls:["এনক্রিপ্টেড না (http)","যা লিখবেন, পথে কেউ পড়ে ফেলতে পারে।"], no_scheme:["http/https নেই","আমরা ওয়েব ঠিকানা হিসেবে চেক করেছি।"], idn:["অন্য ভাষার অক্ষর","ঠিকানায় অন্য বর্ণমালার অক্ষর আছে।"], lookalike:["একই রকম দেখতে ঠিকানা","অক্ষর বদলে আসল কোম্পানির সাইটের মতো সাজানো।"], deceptive_subdomain:["নকল সাবডোমেইন","কোম্পানির নাম শুধু শুরুতে। আসল সাইট শেষের অংশটা।"], brand_in_host:["কোম্পানির নাম, ভুল সাইট","ঠিকানায় কোম্পানির নাম আছে, কিন্তু সাইটটা তাদের না।"], shortener:["শর্ট লিংক","আসল ঠিকানা লুকানো। আমরা ফলো করি না।"], path_bait:["টোপের শব্দ","login, verify, bonus এসব শব্দ স্ক্যাম পেজে বেশি থাকে।"], known_harmful:["আমাদের স্ক্যাম লিস্টে","ডেমোর জন্য বানানো স্ক্যাম সাইটের লিস্ট।"], official:["অফিশিয়াল ডোমেইন","আমাদের লিস্টের কোম্পানির সাইটের সাথে মেলে।"], user_trusted:["আপনার ভরসার সাইট","আপনি যোগ করেছেন। এটা প্রমাণ না।"], danger_scheme:["বিপজ্জনক ধরনের লিংক","এমন লিংক কোড চালাতে পারে। কখনো খুলবেন না।"]},
  copySafe:"সেফ কপি নিন", copied:"কপি হয়েছে (সেফ, ক্লিক হবে না)", copyFail:"কপি হয়নি। লেখাটা সিলেক্ট করে কপি করুন।", trustBtn:"এই সাইটে ভরসা করি", untrustBtn:"লিস্ট থেকে সরান", trustedToast:"ভরসার লিস্টে যোগ হলো", untrustedToast:"লিস্ট থেকে সরানো হলো",
  localNote:"এই ফোনেই চেক হয়েছে। কিছুই পাঠানো হয়নি।", provNote:(r,b)=>`চেক: ফোনেই · লিস্ট: ${r} · ${b}`,
  onlineTitle:"বাড়তি অনলাইন চেক (চাইলে)",
  dnsTitle:"ডোমেইন আর DNS", dnsBody:"DNS সার্ভিসকে জিজ্ঞেস করি: এই সাইটের নাম আছে কি না, আর কোথায় যায়।", dnsBtn:"অনলাইনে চেক",
  dnsConsent:h=>`শুধু সাইটের নাম <b>${h}</b> Google Public DNS (dns.google)-এ যাবে। আপনার চ্যাট বা পুরো লিংক যাবে না।`, allowOnce:"শুধু এবার", allowAlways:"সবসময় অনুমতি", cancel:"বাদ দিন",
  dnsOff:"সেটিংসে অনলাইন চেক বন্ধ আছে।", dnsLoading:"চেক হচ্ছে…", dnsNA:"এই লিংকে হয় না (IP বা প্রাইভেট ঠিকানা)।",
  dnsRes:{complete:"সাইটের নাম আছে", nx:"এই নামে এখন কোনো সাইট নেই", noaddr:"নাম আছে, কিন্তু ঠিকানা নেই", offline:"DNS সার্ভিসে পৌঁছানো যায়নি (অফলাইন বা এখানে বন্ধ)"},
  dnsRows:{addr:"ঠিকানা", cname:"যেখানে যায়", ns:"নেম সার্ভার", when:"চেকের সময়", prov:"সার্ভিস"},
  dnsCaveat:"DNS শুধু দেখায় নামটা কোথায় যায়। সাইটটা কার বা সেফ কি না, তা প্রমাণ করে না।",
  tlsTitle:"ওয়েবসাইট কানেকশন (HTTPS)", tlsBody:"চেক হয়নি: এর জন্য FraudShield হেল্পার লাগবে (আসছে)। ওয়েব পেজ সাইটের সার্টিফিকেট পড়তে পারে না।", tlsHttp:"এই লিংক http, মানে একদমই এনক্রিপ্টেড না।", tlsHttps:"লিংকটা https। মনে রাখবেন: তালা মানে এনক্রিপ্টেড, ভরসার যোগ্য না।",
  notChecked:"চেক হয়নি",
  fileCta:"অ্যাপ বা ফাইল বাছুন", fileLimit:"APK, PDF, ছবি, ডকুমেন্ট… ৫০ MB পর্যন্ত", fileNote:"আমরা ফাইল খুলি না, ইনস্টল করি না, আপলোডও করি না। এই ফোনেই পড়ে তারপর মুছে ফেলি।",
  fileEx:[["fake","নকল বিকাশ আপডেট (APK)"],["disguised","“Payment_Receipt.pdf”"],["calc","সাধারণ ক্যালকুলেটর (APK)"]], fileExLbl:"নমুনা দেখুন:", fileSampleTip:"নিরাপদ ডেমো ফাইল|এতে কোনো কোড নেই, চলতেও পারে না। ডেমোর জন্য বানানো।",
  fileV:{high:["বেশি ঝুঁকি","ফাইলটা বিপজ্জনক বা ছদ্মবেশে আছে। খুলবেন না, ইনস্টল করবেন না।"], verify:["সাবধান থাকুন","এই ফাইল কোড চালাতে পারে, বা আমরা নিশ্চিত না।"], low:["সমস্যা পাইনি","সাধারণ ফাইলের মতো। আমরা খুলিনি, তাই পুরো নিশ্চিত না।"]},
  fileRows:{name:"ফাইলের নাম", type:"আসল ধরন", size:"সাইজ", hash:"ফিঙ্গারপ্রিন্ট (SHA-256)", list:"স্ক্যাম লিস্ট"},
  kinds:{apk:"Android অ্যাপ (APK)", zip:"ZIP ফাইল", ooxml:"Office ডকুমেন্ট", ole:"পুরনো Office ডকুমেন্ট (ম্যাক্রো থাকতে পারে)", pdf:"PDF", exe:"Windows প্রোগ্রাম", elf:"Linux প্রোগ্রাম", dex:"Android কোড", image:"ছবি", html:"ওয়েব পেজ (HTML)", script:"স্ক্রিপ্ট", text:"লেখা", unknown:"অজানা"},
  hashKnown:x=>`মিলেছে: ${x}`, hashUnknown:"আমাদের লিস্টে নেই (তার মানে এটা সেফ না-ও হতে পারে)",
  fileFlag:{disguised:["ছদ্মবেশী ফাইল","নাম বলছে এক, কিন্তু ফাইলটা আসলে অন্য কিছু।"], double_ext:["ডাবল এক্সটেনশন","photo.jpg.exe এমন নাম আসল ধরন লুকায়।"], known_hash:["চেনা খারাপ ফাইল","এই ফাইলটা হুবহু আমাদের লিস্টে আছে।"], apk_impersonation:["নকল কোম্পানির অ্যাপ","কোম্পানির নাম ব্যবহার করছে, কিন্তু এটা তাদের অফিশিয়াল অ্যাপ না।"]},
  apkTitle:"অ্যাপের ভেতরে", apkRows:{label:"অ্যাপের নাম", pkg:"প্যাকেজ", version:"ভার্সন", claims:"যার নাম ব্যবহার করছে", official:"অফিশিয়াল অ্যাপ?", signed:"সিগনেচার", exported:"খোলা দরজা"},
  yes:"হ্যাঁ", no:"না", unknownV:"জানা নেই", officialNo:"না, অফিশিয়াল প্যাকেজ না", officialYes:"অফিশিয়াল প্যাকেজের সাথে মেলে (তবু Play Store থেকেই নিন)", signedTip:"সিগনেচার চেক|কে অ্যাপটা সাইন করেছে, সেই চেক পরে আসছে। শুধু সিগনেচার থাকলেই অ্যাপ সেফ না।",
  exportedTip:"খোলা দরজা|অ্যাপের যে অংশ অন্য অ্যাপ চালু করতে পারে। স্ক্যাম অ্যাপ এগুলো দিয়ে ব্যাকগ্রাউন্ডে চলে।",
  permTitle:"অ্যাপটা যা চায়", permMore:n=>`আরও ${n}টা`, permNone:"ঝুঁকির কোনো পারমিশন পাইনি।",
  perm:{READ_SMS:"আপনার SMS পড়বে, OTP-সহ", RECEIVE_SMS:"নতুন SMS ধরবে, OTP-সহ", SEND_SMS:"আপনার ফোন থেকে SMS পাঠাবে", BIND_ACCESSIBILITY_SERVICE:"আপনার স্ক্রিন দেখবে, আপনার হয়ে চাপ দেবে", SYSTEM_ALERT_WINDOW:"অন্য অ্যাপের ওপর নকল স্ক্রিন দেখাবে", BIND_NOTIFICATION_LISTENER_SERVICE:"আপনার নোটিফিকেশন পড়বে, OTP-সহ", REQUEST_INSTALL_PACKAGES:"অন্য অ্যাপ ইনস্টল করবে", READ_CONTACTS:"কন্টাক্ট লিস্ট পড়বে", CALL_PHONE:"কল করবে", READ_CALL_LOG:"কল হিস্টরি পড়বে", READ_PHONE_STATE:"ফোনের তথ্য পড়বে", BIND_DEVICE_ADMIN:"আনইনস্টল করা কঠিন হবে", QUERY_ALL_PACKAGES:"দেখবে কোন ব্যাংকিং অ্যাপ আছে", RECORD_AUDIO:"মাইক ব্যবহার করবে", CAMERA:"ক্যামেরা ব্যবহার করবে", ACCESS_FINE_LOCATION:"আপনার ঠিক লোকেশন জানবে"},
  fileAct:{store_only:"অ্যাপ শুধু Google Play থেকে নিন। চ্যাটের লিংক থেকে কখনো না।", never_run:"এই প্রোগ্রাম কখনো চালাবেন না।", dont_open:"এই ওয়েব ফাইল খুলবেন না।", no_macros:"ম্যাক্রো বা এডিটিং চালু করবেন না।", delete:"ফাইলটা ডিলিট করুন।", careful:"আশা করে থাকলেই খুলুন।"},
  fileDos:{store:"অ্যাপ শুধু Play Store থেকে", delete:"ফাইলটা ডিলিট করুন", access:"অচেনা অ্যাপকে “Accessibility” দেবেন না", call:"কোম্পানির অফিশিয়াল নম্বরে ফোন করুন"},
  sandboxTitle:"গভীর আচরণ চেক", sandboxBody:"বন্ধ। সন্দেহজনক অ্যাপ সেফভাবে চালাতে আলাদা ল্যাব লাগে। এটা এই অ্যাপের অংশ না।",
  fileErr:{too_big:"ফাইলটা ৫০ MB-এর বেশি।", empty:"ফাইলটা খালি।", read:"ফাইলটা পড়া যায়নি।"},
  qrCta:"QR ছবি বাছুন", qrHelp:"PNG বা JPEG, ৫ MB পর্যন্ত। ভেতরের লিংক পড়ে চেক করি। কখনো খুলি না।", qrReady:"QR পড়ার জন্য তৈরি", qrNoLib:"অফলাইনে QR পড়া যাচ্ছে না (ফাইলের পাশে jsQR.js রাখুন)।", qrNone:"ছবিতে QR পাওয়া যায়নি।", qrBig:"ফাইলটা ৫ MB-এর বেশি।", qrType:"ধরন", qrData:"ভেতরে আছে", qrText:"এই QR-এ লিংক না, লেখা আছে। টাকা দিতে বা কোড বলতে বললে সাবধান।",
  empty:{chat:["ফলাফল এখানে দেখাবে","চ্যাট পেস্ট করুন বা একটা উদাহরণে চাপ দিন।"], link:["একটা লিংক পেস্ট করুন","বা উদাহরণে চাপ দিয়ে এক্স-রে দেখুন।"], file:["অ্যাপ বা ফাইল বাছুন","বা নিরাপদ নমুনা ফাইলগুলো দেখুন।"], qr:["QR ছবি বাছুন","samples ফোল্ডারের নমুনা QR দিয়ে দেখতে পারেন।"]},
  v:{high:["বেশি ঝুঁকি","বিপজ্জনক কিছু চাইছে। থামুন, আগে যাচাই করুন।"],
     verify:["সাবধান: আগে যাচাই করুন","কিছু সন্দেহের চিহ্ন আছে। যাচাই করে তারপর।"],
     low:["যথেষ্ট প্রমাণ নেই","এখনো বিপজ্জনক কিছু চায়নি। তবু এটা “সেফ” না।"],
     abstain:["বোঝার মতো তথ্য নেই","আরও চ্যাট পেস্ট করুন।"]},
  gaugeTip:"রুল স্কোর|যত সন্দেহের চিহ্ন পেয়েছি, তার যোগফল। এটা পার্সেন্ট বা সম্ভাবনা না।",
  firstAlert:(a,s)=>`${a} নম্বর মেসেজে সতর্কতা`+(s&&s<a?` · ${s} নম্বর থেকে সন্দেহ`:""),
  lowReasons:[["পিন, OTP, টাকা বা লিংক চায়নি","গোপন কোড, টাকা, অ্যাপ বা লিংক চাইছে কি না দেখি।"],["তাড়া, ভয় বা লুকোচুরি নেই","প্রতারকরা তাড়া দেয়, ভয় দেখায়, কাউকে বলতে মানা করে।"]],
  todo:"এখনই যা করবেন", replay:"আবার দেখুন", report:"রিপোর্ট", stop:"থামান",
  fbQ:"ঠিক বলেছে?", fb:["হ্যাঁ","না","জানি না"], fbDone:"ধন্যবাদ! শুধু এই ফোনে সেভ হলো।",
  detConvo:"চ্যাট", detSec:"সিকিউরিটি চেক", detEv:"প্রমাণ",
  msg:"মেসেজ", selfNote:"আপনার মেসেজ",
  baseToggle:"সাধারণ স্প্যাম ফিল্টারের সাথে মিলিয়ে দেখুন", baseScam:"ফিল্টার: স্ক্যাম", baseOk:"ফিল্টার: ঠিক",
  stageNames:{hook:"টোপ",trust:"ভরসা",pressure:"চাপ",extraction:"আসল চাওয়া",exit:"সরে পড়া"},
  stageTip:{hook:"মনোযোগ টানে: পুরস্কার, সমস্যা, পার্সেল।",trust:"ভরসা জমায়: “হেড অফিস থেকে বলছি”, “আমি তোমার ছেলে”।",pressure:"চাপ দেয়: সময় বেঁধে দেয়, ভয় দেখায়, কাউকে বলতে মানা করে।",extraction:"আসল চাওয়া: কোড, টাকা, অ্যাপ বা লিংক।",exit:"চিহ্ন মোছে: “মেসেজ ডিলিট করুন”, “কাউকে বলবেন না”।"},
  stagesTitle:"স্ক্যামের ধাপ (AI-এর আন্দাজ)",
  patTitle:"চেনা স্ক্যাম প্যাটার্ন", patNone:"এখনো পুরো কোনো প্যাটার্ন মেলেনি।", patTip:"স্ক্যাম প্যাটার্ন|অ্যালার্মের নিয়মের মতো: পরপর কয়েকটা চেনা ধাপ। শুধু এ পর্যন্ত আসা মেসেজ দেখি।", patToast:n=>`স্ক্যাম প্যাটার্ন ধরা পড়েছে: ${n}`,
  pat:{office:["নকল অফিসের কৌশল",["অফিসের পরিচয়","চাপ","কোড / অ্যাপ চাওয়া"]], linkcode:["আগে লিংক, পরে কোড",["লিংক","কোড / NID চাওয়া"]], prize:["পুরস্কারের ফাঁদ",["পুরস্কার / অফার","টাকা / লিংক / কোড"]], relative:["“আত্মীয়ের” বিপদ",["নতুন নম্বরে আত্মীয়","টাকা চাওয়া"]], refund:["টাকা ফেরতের কৌশল",["“ভুল করে পাঠিয়েছি”","টাকা ফেরত চাওয়া"]], remote:["রিমোট কন্ট্রোলের ফাঁদ",["সার্ভিসের পরিচয়","অ্যাপ ইনস্টল"]]},
  ck:{id:"আসলে কে?", cred:"পিন / OTP", link:"লিংক", manip:"ধোঁকা আটকানো"},
  ckTip:{id:"পরিচয় বনাম নম্বর (F1)|যে পরিচয় দিচ্ছে আর মেসেজ যেখান থেকে এসেছে, দুটো মেলাই।", cred:"পিন / OTP সেফটি (F3)|“কোড দিন” আর “কোড দেবেন না” আলাদা করি। কোড ঢাকা থাকে।", link:"লিংক এক্স-রে (F2)|প্রতিটা লিংকের আসল সাইট বের করি। কখনো খুলি না।", manip:"ধোঁকা আটকানো (F7)|FraudShield-কে হুকুম দেওয়ার চেষ্টা নিজেই সন্দেহের চিহ্ন।"},
  st:{mismatch:"মেলেনি", matched:"নাম মেলে", unknown:"জানা নেই", none:"দাবি নেই", asked:"চাইছে!", advice:"শুধু সাবধানবাণী", mention:"উল্লেখ", clean:"নেই", flagged:"বিপদ চিহ্ন", ok:"স্বাভাবিক", trick:"ধোঁকা আছে", noTrick:"পরিষ্কার"},
  claimed:"দাবি", noClaim:"কোনো কোম্পানি না", family:"পরিবারের কেউ",
  chan:{matched:"নাম আমাদের লিস্টের সাথে মেলে। এটা শুধু নম্বর/নাম মেলানো, মানুষটা না; নাম নকল করা যায়।", mismatched:"এই কোম্পানি অফিশিয়াল নম্বর ব্যবহার করে, কিন্তু এটা পার্সোনাল নম্বর।", unknown_no_sender:"কে পাঠিয়েছে জানা নেই, তাই পরিচয় মেলানো যায়নি।", unknown_alpha_not_listed:"এই নাম আমাদের লিস্টে নেই।", contact:"সেভ করা নম্বর (অ্যাপ যাচাই করেনি)।", na:"চ্যাটে কেউ পরিচয় দেয়নি।", unknown:"জানা নেই।"},
  link:{reg:"আসল সাইট",official:"অফিশিয়াল সাইটের সাথে মেলে",userinfo:"লুকানো ঠিকানা: “@”-এর আগের অংশ ভুয়া",ip:"নাম ছাড়া শুধু IP ঠিকানা",idn:"অদ্ভুত অক্ষর (দুর্বল চিহ্ন)",brand:b=>`“${b}” নাম আছে, কিন্তু এটা ${b}-এর সাইট না`,short:"শর্ট লিংক: আসল ঠিকানা লুকানো",none:"ঠিকানায় বিপদ চিহ্ন নেই",notListed:"লিস্টে না থাকা মানে সেফ না। আমরা লিংক খুলি না।"},
  inspectLink:"লিংকটা এক্স-রে করুন",
  noLinks:"লিংক নেই।", credNone:"পিন বা OTP-র কথা নেই।", cred:{request:"চাইছে",forbid:"“দেবেন না” সাবধানবাণী",mention:"শুধু উল্লেখ",quote:"উদ্ধৃতি"},
  manipOn:"কেউ FraudShield-কে হুকুম দিতে চেয়েছে।", manipOff:"FraudShield-কে ধোঁকা দেওয়ার চেষ্টা নেই।",
  evTitle:"চিহ্ন (ওজন)", cntTitle:"অন্য ব্যাখ্যা",
  benign:{request_money:"চেনা কেউ সত্যিই টাকা চাইতে পারে। তার পুরনো সেভ করা নম্বরে ফোন করুন।", open_link:"আসল সার্ভিসও লিংক পাঠায়। লিংকের বদলে অফিশিয়াল অ্যাপ খুলুন।", authority_claim:"কোম্পানি যোগাযোগ করে, তবে শুধু অফিশিয়াল নম্বর থেকে।", relative_claim:"সত্যিই আত্মীয় নতুন নম্বর নিতে পারে। চেনা নম্বরে ফোন করে যাচাই করুন।", lure:"কিছু অফার আসল, কিন্তু আসল অফার আগে টাকা চায় না।"},
  noSender:"কে পাঠিয়েছে যাচাই করা যায়নি: নম্বর/নাম জানা নেই।", gaugeNote:"রুল স্কোর · সম্ভাবনা না",
  todoL:{cred:["পিন বা OTP কাউকে দেবেন না","বিকাশ, নগদ বা ব্যাংক কখনো চায় না।"], install:["ওদের পাঠানো অ্যাপ ইনস্টল করবেন না","AnyDesk বা চ্যাটের APK দিয়ে ফোন ওদের হাতে চলে যায়।"], link:["লিংকে ঢুকবেন না","অফিশিয়াল অ্যাপ খুলুন বা ঠিকানা নিজে লিখুন।"], money:["টাকা দেওয়ার আগে ফোন করুন","আগে থেকে চেনা নম্বরে।"], wrong:["নিজের ব্যালেন্স দেখুন","সত্যি টাকা এলে হেল্পলাইনের মাধ্যমে ফেরত দিন।"], verify:["অফিশিয়াল নম্বরে ফোন করুন","কার্ড বা অফিশিয়াল সাইটের নম্বরে, মেসেজেরটায় না।"], ident:["NID কাউকে দেবেন না","NID, কার্ড বা সেলফি অচেনা কাউকে না।"], manip:["আমাদের ধোঁকা দিতে চাইছে","এটাই সন্দেহের চিহ্ন।"], none:["সতর্ক থাকুন","কোড, টাকা বা লিংক চাইলে আবার চেক করুন।"]},
  sigx:{request_credential:"কোনো আসল কোম্পানির আপনার পিন বা OTP লাগে না।",request_money:"টাকা চাওয়ার সময়েই ক্ষতি হয়।",install_app:"রিমোট অ্যাপ দিয়ে অচেনা কেউ আপনার ফোন চালায়।",open_link:"লিংক নকল লগইন পেজে নিয়ে যেতে পারে।",brand_lookalike:"ঠিকানায় কোম্পানির নাম, কিন্তু সাইটটা অন্য কারো।",url_userinfo:"ব্রাউজার “@”-এর আগের সব বাদ দেয়। আসল সাইট থাকে পরে।",url_ip:"আসল কোম্পানি নাম ব্যবহার করে, শুধু নম্বর না।",url_idn:"কিছু অক্ষর দেখতে এক, কিন্তু আসলে আলাদা।",shortener:"শর্ট লিংক আসল ঠিকানা লুকায়।",share_identity:"NID বা কার্ড নম্বর দিয়ে অন্যের নামে অ্যাকাউন্ট খোলা যায়।",authority_claim:"অফিসের লোক সেজে ভুয়া ভরসা তৈরি করে।",context_claim:"সার্ভিস, চাকরি বা পুরস্কারের কথা দিয়ে স্ক্যাম শুরু হয়।",identity_mismatch:"কোম্পানি পার্সোনাল নম্বর ব্যবহার করে না।",relative_claim:"নতুন নম্বরে “আত্মীয়” পুরনো কৌশল।",urgency:"তাড়া দিলে যাচাইয়ের সময় থাকে না।",threat:"ভয় পেলে মানুষ না ভেবে কাজ করে।",lure:"অবিশ্বাস্য ভালো অফার সাধারণত ভুয়া।",secrecy:"প্রতারক চায় না আপনি কাউকে জিজ্ঞেস করেন।",wrong_send:"“ভুলে পাঠানো” টাকা প্রায়ই ভুয়া।",manipulation:"আসল মেসেজ কখনো FraudShield-কে কিছু বলে না।",combo_authority_cred:"আগে ভরসা, পরে চাওয়া: পুরনো কৌশল।",combo_lure_money:"আগে পুরস্কার, পরে ফি: পুরনো কৌশল।",combo_relative_money:"নতুন নম্বর আর টাকা চাওয়া: আগে যাচাই করুন।",combo_wrong_money:"“ভুলের” গল্প, তারপর টাকা ফেরত চাওয়া।",safety_warning:"“দেবেন না” সাবধানবাণী আসল মেসেজের লক্ষণ।",official_domain:"এই ঠিকানা আমাদের অফিশিয়াল লিস্টে আছে।",channel_matched:"নাম মেলে, তবে নাম নকল করা যায়।"},
  repTitle:"ঘটনার রিপোর্ট", repHelp:"সাহায্যের জন্য, আইনি প্রমাণ না। গোপন তথ্য ঢাকা, লিংক ক্লিক হবে না। কিছুই কোথাও পাঠানো হয় না।", repLoss:"কী হয়েছে / কত ক্ষতি (চাইলে)", repSteps:"এর মধ্যে কী করেছেন (চাইলে)", repInc:"আমার লিংক আর ফাইল চেকও যোগ করুন", repBuild:"আপডেট", repCopy:"কপি", repDel:"ডিলিট", repCopied:"রিপোর্ট কপি হয়েছে", repCopyFail:"কপি হয়নি। লেখাটা সিলেক্ট করে কপি করুন।", repDeleted:"রিপোর্ট ডিলিট হয়েছে",
  patFpTitle:"স্ক্যামের প্যাটার্ন-ছাপ (পাঠানো হয় না)", patFpHelp:"আপনি রাজি হলে শুধু এটুকু যেত: কোনো লেখা, নম্বর বা লিংক না।",
  ftTitle:"১২ স্তরের সুরক্ষা", ftSub:"আইকনের ওপর মাউস রাখলে বিস্তারিত দেখবেন। চাপ দিলে চালু হবে।",
  feats:[
   ["user","F1","আসলে কে?","যে কোম্পানির নাম বলছে, তা পাঠানো নম্বরের সাথে মেলাই। পার্সোনাল নম্বর থেকে “বিকাশ অফিস”? মেলে না। নাম মিললেও সেটা প্রমাণ না।","s12","#38BDF8","#0369A1"],
   ["link","F2","লিংক এক্স-রে","আসল সাইট, একই রকম দেখতে অক্ষর, লুকানো “@”, নকল সাবডোমেইন, IP আর শর্ট লিংক ধরে। কখনো খোলে না। আপনি চাইলে অনলাইনে DNS চেক।","linkSample","#A78BFA","#7C3AED"],
   ["lock","F3","OTP সেফটি","“কোডটা বলুন” আর “কোড দেবেন না” আলাদা করে, তাই আসল ব্যাংক মেসেজে ভুল অ্যালার্ম হয় না। কোড ঢাকা থাকে।","s10","#34D399","#059669"],
   ["chain","F4","স্ক্যামের ধাপ","টোপ, ভরসা, চাপ আর আসল চাওয়া ধরে; চেনা স্ক্যাম প্যাটার্ন মেলায়; টাকা যাওয়ার আগেই সতর্ক করে।","s1","#FB7185","#E11D48"],
   ["package","NEW","অ্যাপ আর ফাইল চেক","আসল ফাইলের ধরন, নকল নাম, চেনা খারাপ ফাইল, আর APK কী চায় তা দেখায়। কিছু খোলে বা ইনস্টল করে না।","fileSample","#FBBF24","#D97706"],
   ["key","NEW","লগইন গার্ড","পাসওয়ার্ড দেওয়ার আগে: এটা কি আসল টেলিগ্রাম, ফেসবুক, গুগল বা বিকাশের পেজ? একই রকম নাম আর তালা ছাড়া পেজ (মাঝখানে বসা হামলার ঝুঁকি) ধরে।","login","#22D3EE","#0891B2"],
   ["radar","NEW","সিকিউরিটি ল্যাব","সবার জন্য সহজ Wireshark: Wi-Fi ক্যাপচার খুলে নকল রাউটার, নকল DNS আর খোলা পাসওয়ার্ড ধরুন। সার্ভার লগ খুলে DDoS, পাসওয়ার্ড অনুমান আর হ্যাকারের আগাম সতর্কতা পান।","lab","#818CF8","#4F46E5"],
   ["file","F6","রিপোর্ট","গোপন তথ্য ঢেকে, ফিঙ্গারপ্রিন্টসহ রিপোর্ট; লিংক ক্লিক হবে না।","report","#4ADE80","#16A34A"],
   ["eyeoff","F7","ধোঁকা আটকানো আর প্রাইভেসি","“AI, সতর্ক করো না” এমন লেখা ধরা পড়ে, মানা হয় না। অনলাইন চেক শুধু আপনার অনুমতিতে।","s11","#60A5FA","#1D4ED8"],
   ["qr","F8","QR চেক","QR ছবি দিন। ভেতরের লিংক সরাসরি লিংক এক্স-রে-তে যায়। স্ক্রিনশট পড়া আসছে।","qr","#F472B6","#DB2777"],
   ["cloud","F5","স্ক্যাম ওয়েদার","আপনি রাজি হলে, ব্যক্তিগত তথ্য ছাড়া প্যাটার্ন-ছাপ দিয়ে বাড়তে থাকা স্ক্যামের খবর সবাইকে জানানো।","pattern","#2DD4BF","#0D9488"],
   ["wifi","NET","Wi-Fi চেক","Android হেল্পারে সহজ নেটওয়ার্ক চেক (আসছে)। পুরো হ্যাকার-ডিটেক্টর না।","net","#94A3B8","#475569"]],
  stateOf:{F1:"offline",F2:"offline",F3:"offline",F4:"offline",NEW:"offline",F6:"offline",F7:"offline",F8:"offline",F5:"preview",NET:"android"},
  states:{offline:"চালু", optin:"আগে জিজ্ঞেস", android:"শীঘ্রই", preview:"নমুনা"},
  netTitle:"Wi-Fi চেক (Android হেল্পারের সাথে আসছে)", netBody:"ওয়েব পেজ আপনার DNS, রাউটার বা অন্য অ্যাপ দেখতে পারে না। তাই আমরা ভান করি না। এই ব্রাউজার যা দেখতে পায়:",
  netSee:(on,t)=>`ইন্টারনেট: ${on ? "অনলাইন" : "অফলাইন"} · কানেকশন: ${t || "এই ব্রাউজার জানায় না"}`,
  netTips:["টাকার লেনদেনে পাবলিক Wi-Fi না, মোবাইল ডাটা ব্যবহার করুন।","পিন দেওয়ার আগে অ্যাড্রেস বারে আসল সাইট কি না দেখুন।","ফোন আর রাউটার আপডেট রাখুন।","Wi-Fi-তে পেজ অদ্ভুত লাগলে ডিসকানেক্ট করে অফিশিয়াল অ্যাপ ব্যবহার করুন।"],
  scTitle:"যেসব স্ক্যাম ধরি", scSub:"কার্ডের ওপর মাউস রাখুন বা চাপ দিন, দেখুন কৌশলটা কী।",
  scams:[
   {id:"s1", art:"call", t:"নকল “অফিস” কল", p:"“হেড অফিস” আপনার কোড চায়।", how:["বিকাশ বা ব্যাংকের লোক সাজে","বলে অ্যাকাউন্ট ব্লক হবে","OTP বা পিন চায়"]},
   {id:"fileSample", art:"fakeapp", t:"নকল অ্যাপ আপডেট", p:"চ্যাটে পাঠানো “আপডেট” APK।", how:["বলে অ্যাপ আপডেট করতে হবে","APK ফাইল বা লিংক পাঠায়","অ্যাপটা আপনার SMS আর OTP পড়ে"], isNew:true},
   {id:"s9", art:"hook", t:"নকল লিংক", p:"দেখতে আসল, কিন্তু আসল না।", how:["অদ্ভুত ঠিকানায় কোম্পানির নাম","“এখনই ভেরিফাই করুন” তাড়া","লগইন পেজে পিন চুরি"]},
   {id:"s4", art:"family", t:"“আম্মু, নতুন নম্বর”", p:"হঠাৎ “আত্মীয়ের” টাকা লাগবে।", how:["অচেনা নম্বর থেকে মেসেজ","সন্তান বা আত্মীয় সাজে","জলদি, গোপনে টাকা চায়"]}],
  scamFlag:"স্ক্যাম", howT:"কৌশলটা যেভাবে কাজ করে", tryIt:"দেখুন",
  bdTitle:"দেখুন স্ক্যাম কীভাবে ধরা পড়ে", bdSub:"নকল “বিকাশ অফিস” কলার। কোড দেওয়ার আগেই FraudShield সতর্ক করে।", phoneSub:"দাবি: বিকাশ হেড অফিস",
  sb:{low:"দেখছি… এখনো ঝুঁকি নেই", verify:"সাবধান: আগে যাচাই", high:"কোড দেবেন না!"},
  stats:[["0.991","একটা পাবলিক বাংলা SMS ডেটাসেটে macro-F1","Stage A বেসলাইন|১,৪০১টা টেস্ট মেসেজ। শুধু একটা একটা মেসেজ। আমাদের লক্ষ্য পুরো চ্যাট।"],["0.989","একই রকম দেখতে অক্ষরেও recall ঠিক থাকে","E6 পাইলট|নকল অক্ষরে বেসলাইন ০.৭৯৭-এ নামে। আমাদের নর্মালাইজার ০.৯৮৯ ফিরিয়ে আনে। শুধু চেনা কৌশলে পরীক্ষা।"],["12/12","ডেমো চ্যাটে ঠিক রায়","প্রোটোটাইপ|৮টা স্ক্যাম ধরা, ৪টা আসল মেসেজে শান্ত। সব উদাহরণ বানানো।"]],
  bdSrc:"গবেষণার ফলাফল; বিস্তারিত প্রপোজালে। লাইভ স্কোর এখনো মাপা হয়নি।",
  tpTitle:"৪টা অভ্যাসে সেফ থাকুন", tpSub:"কার্ডের ওপর মাউস রাখলে বিস্তারিত দেখবেন।",
  tips:[["noshare","পিন বা OTP কাউকে না","বিকাশ, নগদ, রকেট বা ব্যাংক কখনো চায় না। ফোন, SMS, চ্যাট কোনোভাবেই না।"],["callback","চেনা নম্বরে ফোন করুন","কার্ডের পেছনের বা অফিশিয়াল অ্যাপের নম্বর। মেসেজের নম্বর কখনো না।"],["useapp","অ্যাপ শুধু Play Store থেকে","চ্যাটে পাঠানো APK কখনো ইনস্টল করবেন না। লিংকের বদলে অফিশিয়াল অ্যাপ খুলুন।"],["report","দ্রুত জানান","জরুরি ৯৯৯ · বিকাশ ১৬২৪৭ · নগদ ১৬১৬৭ · রকেট ১৬২১৬ · বাংলাদেশ ব্যাংক ১৬২৩৬। অফিশিয়াল সাইটে নম্বর মিলিয়ে নিন।"]],
  pvTitle:"কিছুই যায় না ফোনের বাইরে।", pvSub:"অ্যাকাউন্ট লাগে না। আপলোড নেই। অনলাইন চেক হয় শুধু আপনি চাইলে।",
  pv:[["wifioff","আপনার ফোনেই চলে","চ্যাট, লিংক, QR আর ফাইল চেক সব এই পেজের ভেতরে।"],["lock","SMS পারমিশন লাগে না","ইনবক্স, কন্টাক্ট, নোটিফিকেশন কিছুই পড়ি না।"],["link","লিংক খুলি না","ঠিকানা পড়ি, কখনো ভিজিট করি না।"],["package","ফাইল চালাই না","অ্যাপ আর ফাইল শুধু পড়ি, খুলি বা ইনস্টল করি না।"],["eyeoff","কোড ঢাকা","পিন, OTP আর ফোন নম্বর স্ক্রিনে লুকানো।"],["shield","হুকুম মানে না","মেসেজের ভেতরের লেখা কখনো নির্দেশ না।"]],
  setTitle:"সেটিংস", onlineLbl:"অনলাইন চেক (DNS)", onlineTip:"অনলাইন চেক|শুধু সাইটের নাম Google Public DNS-এ যায়। চ্যাট বা ফাইল কখনো না।", onlineOpts:{ask:"প্রতিবার জিজ্ঞেস", always:"সবসময় অনুমতি", off:"বন্ধ"},
  testLbl:"EICAR টেস্ট সিগনেচার যোগ করুন", testTip:"টেস্ট সিগনেচার|ফাইল চেক ঠিকমতো কাজ করছে কি না দেখার জন্য নিরাপদ টেস্ট ফাইল।",
  trustLbl:"আমার ভরসার সাইট", trustNone:"এখনো কিছু নেই।", wipe:"আমার সব ডেটা ডিলিট করুন", wiped:"ডিলিট হয়েছে। সেটিংস আগের মতো।",
  fabTip:"প্রতারণার শিকার? সাহায্য নিন|হেল্পলাইন দেখতে চাপ দিন।", fabToast:"জরুরি ৯৯৯ · বিকাশ ১৬২৪৭ · নগদ ১৬১৬৭ · রকেট ১৬২১৬",
  foot:'<b>FraudShield BD</b> · Fabliha Afia (সিএসই, বুয়েট)-এর রিসার্চ প্রোটোটাইপ। বিকাশ, নগদ, রকেট বা কোনো ব্যাংকের সাথে সম্পর্কিত না। এখন রুল-ভিত্তিক, হাতে বসানো ওজন; সব উদাহরণ আর নমুনা ফাইল বানানো ও নিরাপদ। এটা অ্যান্টিভাইরাস, ফায়ারওয়াল বা VPN না। প্রতারণার শিকার হলে: ৯৯৯, অথবা কার্ড বা অফিশিয়াল অ্যাপে লেখা নম্বরে (যেমন বিকাশ ১৬২৪৭, নগদ ১৬১৬৭, রকেট ১৬২১৬)। বাংলাদেশ ব্যাংক ১৬২৩৬ · scamcheck.gov.bd।'
 }
};

/* ---------- Compact copy: less text on screen, details go into hover/tap tips ---------- */
Object.assign(T.en, {
  chSub:"Hover or tap anything to learn more.", scSub:"", ftSub:"", tpSub:"", pvSub:"",
  bdSub:"It warns before the code is shared.",
  stats:[["0.991","Bangla SMS test score","Stage A baseline|macro-F1 on 1,401 test messages from a public Bengali SMS dataset. Single messages only; our goal is whole conversations."],["0.989","even with fake letters","E6 pilot|Look-alike letters cut the baseline's recall to 0.797. Our normaliser restored 0.989. Tested on known tricks only."],["12/12","demo chats right","Prototype|8 scams flagged, 4 real messages left calm. All examples are fictional."]],
  bdSrcTip:"Where these numbers come from|Research results from the proposal. The live score in the checker is an uncalibrated rule indicator, not a probability.",
  fileEx:[["fake","Fake bKash app"],["disguised","Fake PDF"],["calc","Calculator app"]],
  fileNote:"Never opened · never uploaded", fileNoteTip:"Your file stays here|We read it on this device, then drop it. Nothing is installed, run or uploaded.",
  more:n=>`More (${n})`, less:"Less",
  realSite:"Real website", pretends:"Pretends to be", usesName:"Uses the name", hiddenPart:"Hidden decoy", details:"Details",
  fileDetails:"File details", wants:"What this app wants", notOfficial:"NOT OFFICIAL", officialStamp:"OFFICIAL NAME", disguisedStamp:"DISGUISED", knownStamp:"KNOWN BAD",
  permShort:{READ_SMS:"Reads SMS", RECEIVE_SMS:"Catches OTP", SEND_SMS:"Sends SMS", BIND_ACCESSIBILITY_SERVICE:"Controls screen", SYSTEM_ALERT_WINDOW:"Fake screens", BIND_NOTIFICATION_LISTENER_SERVICE:"Reads alerts", REQUEST_INSTALL_PACKAGES:"Installs apps", READ_CONTACTS:"Reads contacts", CALL_PHONE:"Makes calls", READ_CALL_LOG:"Call history", READ_PHONE_STATE:"Phone details", BIND_DEVICE_ADMIN:"Hard to remove", QUERY_ALL_PACKAGES:"Sees your apps", RECORD_AUDIO:"Microphone", CAMERA:"Camera", ACCESS_FINE_LOCATION:"Location"},
  linkActShort:{delete:"Don't open. Delete it.", dont_open:"Don't open it", careful:"Be careful", short:"Ask for the full link", use_app:"Use the official app", your_choice:"Never type PIN or OTP"},
  fileActShort:{store_only:"Play Store only", never_run:"Never run it", dont_open:"Don't open it", no_macros:"No macros", delete:"Delete it", careful:"Be careful"},
  fileDosShort:{store:"Play Store only", delete:"Delete the file", access:"No “Accessibility”", call:"Call the official number"},
  settingsTitle:"Settings", whyLbl:"Why", patLbl:"Pattern:",
  foot:'<b>FraudShield BD</b> · research prototype by Fabliha Afia (CSE, BUET)<br>Not affiliated with bKash, Nagad, Rocket or any bank · Examples are fictional · Scammed? Call 999 or your provider (bKash 16247 · Nagad 16167 · Rocket 16216)'
});
Object.assign(T.bn, {
  chSub:"যেকোনো কিছুর ওপর মাউস রাখুন বা চাপ দিন, বিস্তারিত দেখবেন।", scSub:"", ftSub:"", tpSub:"", pvSub:"",
  bdSub:"কোড দেওয়ার আগেই সতর্ক করে।",
  stats:[["0.991","বাংলা SMS টেস্টে স্কোর","Stage A বেসলাইন|একটা পাবলিক বাংলা SMS ডেটাসেটের ১,৪০১টা টেস্ট মেসেজে macro-F1। শুধু একটা একটা মেসেজ; আমাদের লক্ষ্য পুরো চ্যাট।"],["0.989","নকল অক্ষরেও ঠিক থাকে","E6 পাইলট|নকল অক্ষরে বেসলাইন ০.৭৯৭-এ নামে। আমাদের নর্মালাইজার ০.৯৮৯ ফিরিয়ে আনে। শুধু চেনা কৌশলে পরীক্ষা।"],["12/12","ডেমো চ্যাটে ঠিক","প্রোটোটাইপ|৮টা স্ক্যাম ধরা, ৪টা আসল মেসেজে শান্ত। সব উদাহরণ বানানো।"]],
  bdSrcTip:"সংখ্যাগুলো কোথা থেকে|প্রপোজালের গবেষণার ফলাফল। চেকারের লাইভ স্কোর রুল-ভিত্তিক, সম্ভাবনা না।",
  fileEx:[["fake","নকল বিকাশ অ্যাপ"],["disguised","নকল PDF"],["calc","ক্যালকুলেটর অ্যাপ"]],
  fileNote:"খোলা হয় না · আপলোড হয় না", fileNoteTip:"ফাইল আপনার কাছেই থাকে|এই ফোনেই পড়ি, তারপর মুছে ফেলি। কিছু ইনস্টল, চালু বা আপলোড হয় না।",
  more:n=>`আরও (${n})`, less:"কম দেখান",
  realSite:"আসল ওয়েবসাইট", pretends:"সাজছে যেন", usesName:"নাম ব্যবহার করছে", hiddenPart:"লুকানো ধোঁকা", details:"বিস্তারিত",
  fileDetails:"ফাইলের বিস্তারিত", wants:"অ্যাপটা যা চায়", notOfficial:"অফিশিয়াল না", officialStamp:"অফিশিয়াল নাম", disguisedStamp:"ছদ্মবেশী", knownStamp:"চেনা খারাপ",
  permShort:{READ_SMS:"SMS পড়ে", RECEIVE_SMS:"OTP ধরে", SEND_SMS:"SMS পাঠায়", BIND_ACCESSIBILITY_SERVICE:"স্ক্রিন চালায়", SYSTEM_ALERT_WINDOW:"নকল স্ক্রিন", BIND_NOTIFICATION_LISTENER_SERVICE:"নোটিফিকেশন পড়ে", REQUEST_INSTALL_PACKAGES:"অ্যাপ ইনস্টল করে", READ_CONTACTS:"কন্টাক্ট পড়ে", CALL_PHONE:"কল করে", READ_CALL_LOG:"কল হিস্টরি", READ_PHONE_STATE:"ফোনের তথ্য", BIND_DEVICE_ADMIN:"মোছা কঠিন", QUERY_ALL_PACKAGES:"আপনার অ্যাপ দেখে", RECORD_AUDIO:"মাইক", CAMERA:"ক্যামেরা", ACCESS_FINE_LOCATION:"লোকেশন"},
  linkActShort:{delete:"খুলবেন না, ডিলিট করুন", dont_open:"খুলবেন না", careful:"সাবধান থাকুন", short:"পুরো লিংক চেয়ে নিন", use_app:"অফিশিয়াল অ্যাপ খুলুন", your_choice:"পিন বা OTP দেবেন না"},
  fileActShort:{store_only:"শুধু Play Store", never_run:"কখনো চালাবেন না", dont_open:"খুলবেন না", no_macros:"ম্যাক্রো না", delete:"ডিলিট করুন", careful:"সাবধান থাকুন"},
  fileDosShort:{store:"শুধু Play Store", delete:"ফাইল ডিলিট করুন", access:"“Accessibility” দেবেন না", call:"অফিশিয়াল নম্বরে ফোন"},
  settingsTitle:"সেটিংস", whyLbl:"কেন", patLbl:"প্যাটার্ন:",
  foot:'<b>FraudShield BD</b> · রিসার্চ প্রোটোটাইপ: Fabliha Afia (সিএসই, বুয়েট)<br>বিকাশ, নগদ, রকেট বা কোনো ব্যাংকের সাথে সম্পর্কিত না · সব উদাহরণ বানানো · প্রতারণার শিকার? ৯৯৯ বা প্রোভাইডারকে ফোন করুন (বিকাশ ১৬২৪৭ · নগদ ১৬১৬৭ · রকেট ১৬২১৬)'
});
